# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Action(object):
    NONE = 0
    CatFeed = 1
    RatAttack = 2
    RatNap = 3
    RatCollision = 4
    PlaceDirt = 5
    BreakDirt = 6
    CheesePickup = 7
    CheeseSpawn = 8
    CheeseTransfer = 9
    CatScratch = 10
    CatPounce = 11
    PlaceTrap = 12
    RemoveTrap = 13
    TriggerTrap = 14
    ThrowRat = 15
    UpgradeToRatKing = 16
    RatSqueak = 17
    DamageAction = 18
    StunAction = 19
    SpawnAction = 20
    DieAction = 21
    IndicatorStringAction = 22
    IndicatorDotAction = 23
    IndicatorLineAction = 24
