# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Action(object):
    NONE = 0
    CatFeed = 1
    RatAttack = 2
    RatNap = 3
    RatCollision = 4
    PlaceDirt = 5
    BreakDirt = 6
    CheesePickup = 7
    CheeseSpawn = 8
    CheeseTransfer = 9
    CatScratch = 10
    CatPounce = 11
    PlaceTrap = 12
    TriggerTrap = 13
    ThrowRat = 14
    UpgradeToRatKing = 15
    RatSqueak = 16
    DamageAction = 17
    StunAction = 18
    SpawnAction = 19
    DieAction = 20
    IndicatorStringAction = 21
    IndicatorDotAction = 22
    IndicatorLineAction = 23
