# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from ..schema.InitialBodyTable import InitialBodyTable
from ..schema.Vec import Vec
from ..schema.VecTable import VecTable
from typing import Optional
np = import_numpy()

class GameMap(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameMap()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameMap(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameMap
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GameMap
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GameMap
    def Size(self) -> Optional[Vec]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMap
    def Symmetry(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GameMap
    def InitialBodies(self) -> Optional[InitialBodyTable]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = InitialBodyTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMap
    def RandomSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GameMap
    def Walls(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # GameMap
    def WallsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # GameMap
    def WallsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def WallsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # GameMap
    def Dirt(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # GameMap
    def DirtAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # GameMap
    def DirtLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def DirtIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # GameMap
    def Cheese(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # GameMap
    def CheeseAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # GameMap
    def CheeseLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def CheeseIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # GameMap
    def CheeseMines(self) -> Optional[VecTable]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMap
    def CatWaypointIds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # GameMap
    def CatWaypointIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # GameMap
    def CatWaypointIdsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def CatWaypointIdsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # GameMap
    def CatWaypointVecs(self, j: int) -> Optional[VecTable]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMap
    def CatWaypointVecsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def CatWaypointVecsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def GameMapStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    GameMapStart(builder)

def GameMapAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    GameMapAddName(builder, name)

def GameMapAddSize(builder: flatbuffers.Builder, size: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(size), 0)

def AddSize(builder: flatbuffers.Builder, size: Any):
    GameMapAddSize(builder, size)

def GameMapAddSymmetry(builder: flatbuffers.Builder, symmetry: int):
    builder.PrependInt32Slot(2, symmetry, 0)

def AddSymmetry(builder: flatbuffers.Builder, symmetry: int):
    GameMapAddSymmetry(builder, symmetry)

def GameMapAddInitialBodies(builder: flatbuffers.Builder, initialBodies: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(initialBodies), 0)

def AddInitialBodies(builder: flatbuffers.Builder, initialBodies: int):
    GameMapAddInitialBodies(builder, initialBodies)

def GameMapAddRandomSeed(builder: flatbuffers.Builder, randomSeed: int):
    builder.PrependInt32Slot(4, randomSeed, 0)

def AddRandomSeed(builder: flatbuffers.Builder, randomSeed: int):
    GameMapAddRandomSeed(builder, randomSeed)

def GameMapAddWalls(builder: flatbuffers.Builder, walls: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(walls), 0)

def AddWalls(builder: flatbuffers.Builder, walls: int):
    GameMapAddWalls(builder, walls)

def GameMapStartWallsVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartWallsVector(builder, numElems: int) -> int:
    return GameMapStartWallsVector(builder, numElems)

def GameMapAddDirt(builder: flatbuffers.Builder, dirt: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(dirt), 0)

def AddDirt(builder: flatbuffers.Builder, dirt: int):
    GameMapAddDirt(builder, dirt)

def GameMapStartDirtVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartDirtVector(builder, numElems: int) -> int:
    return GameMapStartDirtVector(builder, numElems)

def GameMapAddCheese(builder: flatbuffers.Builder, cheese: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(cheese), 0)

def AddCheese(builder: flatbuffers.Builder, cheese: int):
    GameMapAddCheese(builder, cheese)

def GameMapStartCheeseVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartCheeseVector(builder, numElems: int) -> int:
    return GameMapStartCheeseVector(builder, numElems)

def GameMapAddCheeseMines(builder: flatbuffers.Builder, cheeseMines: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(cheeseMines), 0)

def AddCheeseMines(builder: flatbuffers.Builder, cheeseMines: int):
    GameMapAddCheeseMines(builder, cheeseMines)

def GameMapAddCatWaypointIds(builder: flatbuffers.Builder, catWaypointIds: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(catWaypointIds), 0)

def AddCatWaypointIds(builder: flatbuffers.Builder, catWaypointIds: int):
    GameMapAddCatWaypointIds(builder, catWaypointIds)

def GameMapStartCatWaypointIdsVector(builder, numElems: int) -> int:
    return builder.StartVector(2, numElems, 2)

def StartCatWaypointIdsVector(builder, numElems: int) -> int:
    return GameMapStartCatWaypointIdsVector(builder, numElems)

def GameMapAddCatWaypointVecs(builder: flatbuffers.Builder, catWaypointVecs: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(catWaypointVecs), 0)

def AddCatWaypointVecs(builder: flatbuffers.Builder, catWaypointVecs: int):
    GameMapAddCatWaypointVecs(builder, catWaypointVecs)

def GameMapStartCatWaypointVecsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCatWaypointVecsVector(builder, numElems: int) -> int:
    return GameMapStartCatWaypointVecsVector(builder, numElems)

def GameMapEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GameMapEnd(builder)
