from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class GameplayConstants(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> GameplayConstants: ...
  @classmethod
  def GetRootAsGameplayConstants(cls, buf: bytes, offset: int) -> GameplayConstants: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
def GameplayConstantsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def GameplayConstantsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

