from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from ..schema.InitialBodyTable import InitialBodyTable
from ..schema.Vec import Vec
from ..schema.VecTable import VecTable

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class GameMap(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> GameMap: ...
  @classmethod
  def GetRootAsGameMap(cls, buf: bytes, offset: int) -> GameMap: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Size(self) -> Vec | None: ...
  def Symmetry(self) -> int: ...
  def InitialBodies(self) -> InitialBodyTable | None: ...
  def RandomSeed(self) -> int: ...
  def Walls(self, i: int) -> typing.List[bool]: ...
  def WallsAsNumpy(self) -> np.ndarray: ...
  def WallsLength(self) -> int: ...
  def WallsIsNone(self) -> bool: ...
  def Dirt(self, i: int) -> typing.List[bool]: ...
  def DirtAsNumpy(self) -> np.ndarray: ...
  def DirtLength(self) -> int: ...
  def DirtIsNone(self) -> bool: ...
  def Cheese(self, i: int) -> typing.List[int]: ...
  def CheeseAsNumpy(self) -> np.ndarray: ...
  def CheeseLength(self) -> int: ...
  def CheeseIsNone(self) -> bool: ...
  def CheeseMines(self) -> VecTable | None: ...
  def CatWaypointIds(self, i: int) -> typing.List[int]: ...
  def CatWaypointIdsAsNumpy(self) -> np.ndarray: ...
  def CatWaypointIdsLength(self) -> int: ...
  def CatWaypointIdsIsNone(self) -> bool: ...
  def CatWaypointVecs(self, i: int) -> VecTable | None: ...
  def CatWaypointVecsLength(self) -> int: ...
  def CatWaypointVecsIsNone(self) -> bool: ...
def GameMapStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def GameMapAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def GameMapAddSize(builder: flatbuffers.Builder, size: uoffset) -> None: ...
def GameMapAddSymmetry(builder: flatbuffers.Builder, symmetry: int) -> None: ...
def GameMapAddInitialBodies(builder: flatbuffers.Builder, initialBodies: uoffset) -> None: ...
def GameMapAddRandomSeed(builder: flatbuffers.Builder, randomSeed: int) -> None: ...
def GameMapAddWalls(builder: flatbuffers.Builder, walls: uoffset) -> None: ...
def GameMapStartWallsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartWallsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GameMapAddDirt(builder: flatbuffers.Builder, dirt: uoffset) -> None: ...
def GameMapStartDirtVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDirtVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GameMapAddCheese(builder: flatbuffers.Builder, cheese: uoffset) -> None: ...
def GameMapStartCheeseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCheeseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GameMapAddCheeseMines(builder: flatbuffers.Builder, cheeseMines: uoffset) -> None: ...
def GameMapAddCatWaypointIds(builder: flatbuffers.Builder, catWaypointIds: uoffset) -> None: ...
def GameMapStartCatWaypointIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCatWaypointIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GameMapAddCatWaypointVecs(builder: flatbuffers.Builder, catWaypointVecs: uoffset) -> None: ...
def GameMapStartCatWaypointVecsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCatWaypointVecsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GameMapEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

