from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class IndicatorStringAction(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> IndicatorStringAction: ...
  @classmethod
  def GetRootAsIndicatorStringAction(cls, buf: bytes, offset: int) -> IndicatorStringAction: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Value(self) -> str | None: ...
def IndicatorStringActionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def IndicatorStringActionAddValue(builder: flatbuffers.Builder, value: uoffset) -> None: ...
def IndicatorStringActionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

