from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from ..schema.RobotType import RobotType

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RobotTypeMetadata(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RobotTypeMetadata: ...
  @classmethod
  def GetRootAsRobotTypeMetadata(cls, buf: bytes, offset: int) -> RobotTypeMetadata: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Type(self) -> typing.Literal[RobotType.NONE, RobotType.RAT, RobotType.RAT_KING, RobotType.CAT]: ...
  def ActionCooldown(self) -> int: ...
  def MovementCooldown(self) -> int: ...
  def TurningCooldown(self) -> int: ...
  def BaseHealth(self) -> int: ...
  def MaxCheese(self) -> int: ...
  def VisionConeRadiusSquared(self) -> int: ...
  def VisionConeAngle(self) -> int: ...
  def MessageRadiusSquared(self) -> int: ...
  def BytecodeLimit(self) -> int: ...
def RobotTypeMetadataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RobotTypeMetadataAddType(builder: flatbuffers.Builder, type: typing.Literal[RobotType.NONE, RobotType.RAT, RobotType.RAT_KING, RobotType.CAT]) -> None: ...
def RobotTypeMetadataAddActionCooldown(builder: flatbuffers.Builder, actionCooldown: int) -> None: ...
def RobotTypeMetadataAddMovementCooldown(builder: flatbuffers.Builder, movementCooldown: int) -> None: ...
def RobotTypeMetadataAddTurningCooldown(builder: flatbuffers.Builder, turningCooldown: int) -> None: ...
def RobotTypeMetadataAddBaseHealth(builder: flatbuffers.Builder, baseHealth: int) -> None: ...
def RobotTypeMetadataAddMaxCheese(builder: flatbuffers.Builder, maxCheese: int) -> None: ...
def RobotTypeMetadataAddVisionConeRadiusSquared(builder: flatbuffers.Builder, visionConeRadiusSquared: int) -> None: ...
def RobotTypeMetadataAddVisionConeAngle(builder: flatbuffers.Builder, visionConeAngle: int) -> None: ...
def RobotTypeMetadataAddMessageRadiusSquared(builder: flatbuffers.Builder, messageRadiusSquared: int) -> None: ...
def RobotTypeMetadataAddBytecodeLimit(builder: flatbuffers.Builder, bytecodeLimit: int) -> None: ...
def RobotTypeMetadataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

