from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from ..schema.Turn import Turn

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Round(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Round: ...
  @classmethod
  def GetRootAsRound(cls, buf: bytes, offset: int) -> Round: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TeamIds(self, i: int) -> typing.List[int]: ...
  def TeamIdsAsNumpy(self) -> np.ndarray: ...
  def TeamIdsLength(self) -> int: ...
  def TeamIdsIsNone(self) -> bool: ...
  def TeamCheeseTransferred(self, i: int) -> typing.List[int]: ...
  def TeamCheeseTransferredAsNumpy(self) -> np.ndarray: ...
  def TeamCheeseTransferredLength(self) -> int: ...
  def TeamCheeseTransferredIsNone(self) -> bool: ...
  def TeamCatDamage(self, i: int) -> typing.List[int]: ...
  def TeamCatDamageAsNumpy(self) -> np.ndarray: ...
  def TeamCatDamageLength(self) -> int: ...
  def TeamCatDamageIsNone(self) -> bool: ...
  def TeamAliveRatKings(self, i: int) -> typing.List[int]: ...
  def TeamAliveRatKingsAsNumpy(self) -> np.ndarray: ...
  def TeamAliveRatKingsLength(self) -> int: ...
  def TeamAliveRatKingsIsNone(self) -> bool: ...
  def TeamAliveBabyRats(self, i: int) -> typing.List[int]: ...
  def TeamAliveBabyRatsAsNumpy(self) -> np.ndarray: ...
  def TeamAliveBabyRatsLength(self) -> int: ...
  def TeamAliveBabyRatsIsNone(self) -> bool: ...
  def TeamRatTrapCount(self, i: int) -> typing.List[int]: ...
  def TeamRatTrapCountAsNumpy(self) -> np.ndarray: ...
  def TeamRatTrapCountLength(self) -> int: ...
  def TeamRatTrapCountIsNone(self) -> bool: ...
  def TeamCatTrapCount(self, i: int) -> typing.List[int]: ...
  def TeamCatTrapCountAsNumpy(self) -> np.ndarray: ...
  def TeamCatTrapCountLength(self) -> int: ...
  def TeamCatTrapCountIsNone(self) -> bool: ...
  def TeamDirtAmounts(self, i: int) -> typing.List[int]: ...
  def TeamDirtAmountsAsNumpy(self) -> np.ndarray: ...
  def TeamDirtAmountsLength(self) -> int: ...
  def TeamDirtAmountsIsNone(self) -> bool: ...
  def Turns(self, i: int) -> Turn | None: ...
  def TurnsLength(self) -> int: ...
  def TurnsIsNone(self) -> bool: ...
  def DiedIds(self, i: int) -> typing.List[int]: ...
  def DiedIdsAsNumpy(self) -> np.ndarray: ...
  def DiedIdsLength(self) -> int: ...
  def DiedIdsIsNone(self) -> bool: ...
  def RoundId(self) -> int: ...
def RoundStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RoundAddTeamIds(builder: flatbuffers.Builder, teamIds: uoffset) -> None: ...
def RoundStartTeamIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTeamCheeseTransferred(builder: flatbuffers.Builder, teamCheeseTransferred: uoffset) -> None: ...
def RoundStartTeamCheeseTransferredVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamCheeseTransferredVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTeamCatDamage(builder: flatbuffers.Builder, teamCatDamage: uoffset) -> None: ...
def RoundStartTeamCatDamageVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamCatDamageVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTeamAliveRatKings(builder: flatbuffers.Builder, teamAliveRatKings: uoffset) -> None: ...
def RoundStartTeamAliveRatKingsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamAliveRatKingsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTeamAliveBabyRats(builder: flatbuffers.Builder, teamAliveBabyRats: uoffset) -> None: ...
def RoundStartTeamAliveBabyRatsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamAliveBabyRatsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTeamRatTrapCount(builder: flatbuffers.Builder, teamRatTrapCount: uoffset) -> None: ...
def RoundStartTeamRatTrapCountVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamRatTrapCountVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTeamCatTrapCount(builder: flatbuffers.Builder, teamCatTrapCount: uoffset) -> None: ...
def RoundStartTeamCatTrapCountVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamCatTrapCountVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTeamDirtAmounts(builder: flatbuffers.Builder, teamDirtAmounts: uoffset) -> None: ...
def RoundStartTeamDirtAmountsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTeamDirtAmountsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddTurns(builder: flatbuffers.Builder, turns: uoffset) -> None: ...
def RoundStartTurnsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTurnsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddDiedIds(builder: flatbuffers.Builder, diedIds: uoffset) -> None: ...
def RoundStartDiedIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDiedIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RoundAddRoundId(builder: flatbuffers.Builder, roundId: int) -> None: ...
def RoundEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

