from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from ..schema.Action import Action

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Turn(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Turn: ...
  @classmethod
  def GetRootAsTurn(cls, buf: bytes, offset: int) -> Turn: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def RobotId(self) -> int: ...
  def Health(self) -> int: ...
  def Cheese(self) -> int: ...
  def MoveCooldown(self) -> int: ...
  def TurningCooldown(self) -> int: ...
  def ActionCooldown(self) -> int: ...
  def BytecodesUsed(self) -> int: ...
  def X(self) -> int: ...
  def Y(self) -> int: ...
  def Dir(self) -> int: ...
  def ActionsType(self, i: int) -> typing.Literal[Action.NONE, Action.CatFeed, Action.RatAttack, Action.RatNap, Action.RatCollision, Action.PlaceDirt, Action.BreakDirt, Action.CheesePickup, Action.CheeseSpawn, Action.CheeseTransfer, Action.CatScratch, Action.CatPounce, Action.PlaceTrap, Action.RemoveTrap, Action.TriggerTrap, Action.ThrowRat, Action.UpgradeToRatKing, Action.RatSqueak, Action.DamageAction, Action.StunAction, Action.SpawnAction, Action.DieAction, Action.IndicatorStringAction, Action.IndicatorDotAction, Action.IndicatorLineAction]: ...
  def ActionsTypeAsNumpy(self) -> np.ndarray: ...
  def ActionsTypeLength(self) -> int: ...
  def ActionsTypeIsNone(self) -> bool: ...
  def Actions(self, i: int) -> typing.Literal[Action.NONE, Action.CatFeed, Action.RatAttack, Action.RatNap, Action.RatCollision, Action.PlaceDirt, Action.BreakDirt, Action.CheesePickup, Action.CheeseSpawn, Action.CheeseTransfer, Action.CatScratch, Action.CatPounce, Action.PlaceTrap, Action.RemoveTrap, Action.TriggerTrap, Action.ThrowRat, Action.UpgradeToRatKing, Action.RatSqueak, Action.DamageAction, Action.StunAction, Action.SpawnAction, Action.DieAction, Action.IndicatorStringAction, Action.IndicatorDotAction, Action.IndicatorLineAction]: ...
  def ActionsAsNumpy(self) -> np.ndarray: ...
  def ActionsLength(self) -> int: ...
  def ActionsIsNone(self) -> bool: ...
  def IsCooperation(self) -> bool: ...
def TurnStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TurnAddRobotId(builder: flatbuffers.Builder, robotId: int) -> None: ...
def TurnAddHealth(builder: flatbuffers.Builder, health: int) -> None: ...
def TurnAddCheese(builder: flatbuffers.Builder, cheese: int) -> None: ...
def TurnAddMoveCooldown(builder: flatbuffers.Builder, moveCooldown: int) -> None: ...
def TurnAddTurningCooldown(builder: flatbuffers.Builder, turningCooldown: int) -> None: ...
def TurnAddActionCooldown(builder: flatbuffers.Builder, actionCooldown: int) -> None: ...
def TurnAddBytecodesUsed(builder: flatbuffers.Builder, bytecodesUsed: int) -> None: ...
def TurnAddX(builder: flatbuffers.Builder, x: int) -> None: ...
def TurnAddY(builder: flatbuffers.Builder, y: int) -> None: ...
def TurnAddDir(builder: flatbuffers.Builder, dir: int) -> None: ...
def TurnAddActionsType(builder: flatbuffers.Builder, actionsType: uoffset) -> None: ...
def TurnStartActionsTypeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartActionsTypeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TurnAddActions(builder: flatbuffers.Builder, actions: uoffset) -> None: ...
def TurnStartActionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartActionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TurnAddIsCooperation(builder: flatbuffers.Builder, isCooperation: bool) -> None: ...
def TurnEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

