// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Transfer a cheese between rats
 */
export class CheeseTransfer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CheeseTransfer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * Id of the rat which receives the cheese
 */
id():number {
  return this.bb!.readUint16(this.bb_pos);
}

amount():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createCheeseTransfer(builder:flatbuffers.Builder, id: number, amount: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(amount);
  builder.writeInt16(id);
  return builder.offset();
}

}
