// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RobotType } from '../../battlecode/schema/robot-type';


export class RobotTypeMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RobotTypeMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRobotTypeMetadata(bb:flatbuffers.ByteBuffer, obj?:RobotTypeMetadata):RobotTypeMetadata {
  return (obj || new RobotTypeMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRobotTypeMetadata(bb:flatbuffers.ByteBuffer, obj?:RobotTypeMetadata):RobotTypeMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RobotTypeMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():RobotType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : RobotType.NONE;
}

actionCooldown():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

movementCooldown():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

turningCooldown():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

baseHealth():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

maxCheese():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

visionConeRadiusSquared():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

visionConeAngle():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

messageRadiusSquared():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

bytecodeLimit():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startRobotTypeMetadata(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addType(builder:flatbuffers.Builder, type:RobotType) {
  builder.addFieldInt8(0, type, RobotType.NONE);
}

static addActionCooldown(builder:flatbuffers.Builder, actionCooldown:number) {
  builder.addFieldInt32(1, actionCooldown, 0);
}

static addMovementCooldown(builder:flatbuffers.Builder, movementCooldown:number) {
  builder.addFieldInt32(2, movementCooldown, 0);
}

static addTurningCooldown(builder:flatbuffers.Builder, turningCooldown:number) {
  builder.addFieldInt32(3, turningCooldown, 0);
}

static addBaseHealth(builder:flatbuffers.Builder, baseHealth:number) {
  builder.addFieldInt32(4, baseHealth, 0);
}

static addMaxCheese(builder:flatbuffers.Builder, maxCheese:number) {
  builder.addFieldInt32(5, maxCheese, 0);
}

static addVisionConeRadiusSquared(builder:flatbuffers.Builder, visionConeRadiusSquared:number) {
  builder.addFieldInt32(6, visionConeRadiusSquared, 0);
}

static addVisionConeAngle(builder:flatbuffers.Builder, visionConeAngle:number) {
  builder.addFieldInt32(7, visionConeAngle, 0);
}

static addMessageRadiusSquared(builder:flatbuffers.Builder, messageRadiusSquared:number) {
  builder.addFieldInt32(8, messageRadiusSquared, 0);
}

static addBytecodeLimit(builder:flatbuffers.Builder, bytecodeLimit:number) {
  builder.addFieldInt32(9, bytecodeLimit, 0);
}

static endRobotTypeMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRobotTypeMetadata(builder:flatbuffers.Builder, type:RobotType, actionCooldown:number, movementCooldown:number, turningCooldown:number, baseHealth:number, maxCheese:number, visionConeRadiusSquared:number, visionConeAngle:number, messageRadiusSquared:number, bytecodeLimit:number):flatbuffers.Offset {
  RobotTypeMetadata.startRobotTypeMetadata(builder);
  RobotTypeMetadata.addType(builder, type);
  RobotTypeMetadata.addActionCooldown(builder, actionCooldown);
  RobotTypeMetadata.addMovementCooldown(builder, movementCooldown);
  RobotTypeMetadata.addTurningCooldown(builder, turningCooldown);
  RobotTypeMetadata.addBaseHealth(builder, baseHealth);
  RobotTypeMetadata.addMaxCheese(builder, maxCheese);
  RobotTypeMetadata.addVisionConeRadiusSquared(builder, visionConeRadiusSquared);
  RobotTypeMetadata.addVisionConeAngle(builder, visionConeAngle);
  RobotTypeMetadata.addMessageRadiusSquared(builder, messageRadiusSquared);
  RobotTypeMetadata.addBytecodeLimit(builder, bytecodeLimit);
  return RobotTypeMetadata.endRobotTypeMetadata(builder);
}
}
