// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Action for when a robot is stunned
 */
export class StunAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StunAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id():number {
  return this.bb!.readUint16(this.bb_pos);
}

cooldown():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createStunAction(builder:flatbuffers.Builder, id: number, cooldown: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(cooldown);
  builder.writeInt16(id);
  return builder.offset();
}

}
