// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Throw a rat
 */
export class ThrowRat {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ThrowRat {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * Id of the thrown rat
 */
id():number {
  return this.bb!.readUint16(this.bb_pos);
}

loc():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createThrowRat(builder:flatbuffers.Builder, id: number, loc: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(loc);
  builder.writeInt16(id);
  return builder.offset();
}

}
