"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Action = void 0;
exports.unionToAction = unionToAction;
exports.unionListToAction = unionListToAction;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var break_dirt_1 = require("../../battlecode/schema/break-dirt");
var cat_feed_1 = require("../../battlecode/schema/cat-feed");
var cat_pounce_1 = require("../../battlecode/schema/cat-pounce");
var cat_scratch_1 = require("../../battlecode/schema/cat-scratch");
var cheese_pickup_1 = require("../../battlecode/schema/cheese-pickup");
var cheese_spawn_1 = require("../../battlecode/schema/cheese-spawn");
var cheese_transfer_1 = require("../../battlecode/schema/cheese-transfer");
var damage_action_1 = require("../../battlecode/schema/damage-action");
var die_action_1 = require("../../battlecode/schema/die-action");
var indicator_dot_action_1 = require("../../battlecode/schema/indicator-dot-action");
var indicator_line_action_1 = require("../../battlecode/schema/indicator-line-action");
var indicator_string_action_1 = require("../../battlecode/schema/indicator-string-action");
var place_dirt_1 = require("../../battlecode/schema/place-dirt");
var place_trap_1 = require("../../battlecode/schema/place-trap");
var rat_attack_1 = require("../../battlecode/schema/rat-attack");
var rat_collision_1 = require("../../battlecode/schema/rat-collision");
var rat_nap_1 = require("../../battlecode/schema/rat-nap");
var rat_squeak_1 = require("../../battlecode/schema/rat-squeak");
var remove_trap_1 = require("../../battlecode/schema/remove-trap");
var spawn_action_1 = require("../../battlecode/schema/spawn-action");
var stun_action_1 = require("../../battlecode/schema/stun-action");
var throw_rat_1 = require("../../battlecode/schema/throw-rat");
var trigger_trap_1 = require("../../battlecode/schema/trigger-trap");
var upgrade_to_rat_king_1 = require("../../battlecode/schema/upgrade-to-rat-king");
var Action;
(function (Action) {
    Action[Action["NONE"] = 0] = "NONE";
    Action[Action["CatFeed"] = 1] = "CatFeed";
    Action[Action["RatAttack"] = 2] = "RatAttack";
    Action[Action["RatNap"] = 3] = "RatNap";
    Action[Action["RatCollision"] = 4] = "RatCollision";
    Action[Action["PlaceDirt"] = 5] = "PlaceDirt";
    Action[Action["BreakDirt"] = 6] = "BreakDirt";
    Action[Action["CheesePickup"] = 7] = "CheesePickup";
    Action[Action["CheeseSpawn"] = 8] = "CheeseSpawn";
    Action[Action["CheeseTransfer"] = 9] = "CheeseTransfer";
    Action[Action["CatScratch"] = 10] = "CatScratch";
    Action[Action["CatPounce"] = 11] = "CatPounce";
    Action[Action["PlaceTrap"] = 12] = "PlaceTrap";
    Action[Action["RemoveTrap"] = 13] = "RemoveTrap";
    Action[Action["TriggerTrap"] = 14] = "TriggerTrap";
    Action[Action["ThrowRat"] = 15] = "ThrowRat";
    Action[Action["UpgradeToRatKing"] = 16] = "UpgradeToRatKing";
    Action[Action["RatSqueak"] = 17] = "RatSqueak";
    Action[Action["DamageAction"] = 18] = "DamageAction";
    Action[Action["StunAction"] = 19] = "StunAction";
    Action[Action["SpawnAction"] = 20] = "SpawnAction";
    Action[Action["DieAction"] = 21] = "DieAction";
    Action[Action["IndicatorStringAction"] = 22] = "IndicatorStringAction";
    Action[Action["IndicatorDotAction"] = 23] = "IndicatorDotAction";
    Action[Action["IndicatorLineAction"] = 24] = "IndicatorLineAction";
})(Action || (exports.Action = Action = {}));
function unionToAction(type, accessor) {
    switch (Action[type]) {
        case 'NONE': return null;
        case 'CatFeed': return accessor(new cat_feed_1.CatFeed());
        case 'RatAttack': return accessor(new rat_attack_1.RatAttack());
        case 'RatNap': return accessor(new rat_nap_1.RatNap());
        case 'RatCollision': return accessor(new rat_collision_1.RatCollision());
        case 'PlaceDirt': return accessor(new place_dirt_1.PlaceDirt());
        case 'BreakDirt': return accessor(new break_dirt_1.BreakDirt());
        case 'CheesePickup': return accessor(new cheese_pickup_1.CheesePickup());
        case 'CheeseSpawn': return accessor(new cheese_spawn_1.CheeseSpawn());
        case 'CheeseTransfer': return accessor(new cheese_transfer_1.CheeseTransfer());
        case 'CatScratch': return accessor(new cat_scratch_1.CatScratch());
        case 'CatPounce': return accessor(new cat_pounce_1.CatPounce());
        case 'PlaceTrap': return accessor(new place_trap_1.PlaceTrap());
        case 'RemoveTrap': return accessor(new remove_trap_1.RemoveTrap());
        case 'TriggerTrap': return accessor(new trigger_trap_1.TriggerTrap());
        case 'ThrowRat': return accessor(new throw_rat_1.ThrowRat());
        case 'UpgradeToRatKing': return accessor(new upgrade_to_rat_king_1.UpgradeToRatKing());
        case 'RatSqueak': return accessor(new rat_squeak_1.RatSqueak());
        case 'DamageAction': return accessor(new damage_action_1.DamageAction());
        case 'StunAction': return accessor(new stun_action_1.StunAction());
        case 'SpawnAction': return accessor(new spawn_action_1.SpawnAction());
        case 'DieAction': return accessor(new die_action_1.DieAction());
        case 'IndicatorStringAction': return accessor(new indicator_string_action_1.IndicatorStringAction());
        case 'IndicatorDotAction': return accessor(new indicator_dot_action_1.IndicatorDotAction());
        case 'IndicatorLineAction': return accessor(new indicator_line_action_1.IndicatorLineAction());
        default: return null;
    }
}
function unionListToAction(type, accessor, index) {
    switch (Action[type]) {
        case 'NONE': return null;
        case 'CatFeed': return accessor(index, new cat_feed_1.CatFeed());
        case 'RatAttack': return accessor(index, new rat_attack_1.RatAttack());
        case 'RatNap': return accessor(index, new rat_nap_1.RatNap());
        case 'RatCollision': return accessor(index, new rat_collision_1.RatCollision());
        case 'PlaceDirt': return accessor(index, new place_dirt_1.PlaceDirt());
        case 'BreakDirt': return accessor(index, new break_dirt_1.BreakDirt());
        case 'CheesePickup': return accessor(index, new cheese_pickup_1.CheesePickup());
        case 'CheeseSpawn': return accessor(index, new cheese_spawn_1.CheeseSpawn());
        case 'CheeseTransfer': return accessor(index, new cheese_transfer_1.CheeseTransfer());
        case 'CatScratch': return accessor(index, new cat_scratch_1.CatScratch());
        case 'CatPounce': return accessor(index, new cat_pounce_1.CatPounce());
        case 'PlaceTrap': return accessor(index, new place_trap_1.PlaceTrap());
        case 'RemoveTrap': return accessor(index, new remove_trap_1.RemoveTrap());
        case 'TriggerTrap': return accessor(index, new trigger_trap_1.TriggerTrap());
        case 'ThrowRat': return accessor(index, new throw_rat_1.ThrowRat());
        case 'UpgradeToRatKing': return accessor(index, new upgrade_to_rat_king_1.UpgradeToRatKing());
        case 'RatSqueak': return accessor(index, new rat_squeak_1.RatSqueak());
        case 'DamageAction': return accessor(index, new damage_action_1.DamageAction());
        case 'StunAction': return accessor(index, new stun_action_1.StunAction());
        case 'SpawnAction': return accessor(index, new spawn_action_1.SpawnAction());
        case 'DieAction': return accessor(index, new die_action_1.DieAction());
        case 'IndicatorStringAction': return accessor(index, new indicator_string_action_1.IndicatorStringAction());
        case 'IndicatorDotAction': return accessor(index, new indicator_dot_action_1.IndicatorDotAction());
        case 'IndicatorLineAction': return accessor(index, new indicator_line_action_1.IndicatorLineAction());
        default: return null;
    }
}
