"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlaceTrap = void 0;
/**
 * Place a trap at location
 */
var PlaceTrap = /** @class */ (function () {
    function PlaceTrap() {
        this.bb = null;
        this.bb_pos = 0;
    }
    PlaceTrap.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    PlaceTrap.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    PlaceTrap.prototype.team = function () {
        return this.bb.readInt8(this.bb_pos + 2);
    };
    PlaceTrap.prototype.isRatTrapType = function () {
        return !!this.bb.readInt8(this.bb_pos + 3);
    };
    PlaceTrap.sizeOf = function () {
        return 4;
    };
    PlaceTrap.createPlaceTrap = function (builder, loc, team, isRatTrapType) {
        builder.prep(2, 4);
        builder.writeInt8(Number(Boolean(isRatTrapType)));
        builder.writeInt8(team);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return PlaceTrap;
}());
exports.PlaceTrap = PlaceTrap;
