"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RemoveTrap = void 0;
/**
 * Remove a trap at location
 */
var RemoveTrap = /** @class */ (function () {
    function RemoveTrap() {
        this.bb = null;
        this.bb_pos = 0;
    }
    RemoveTrap.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    RemoveTrap.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    RemoveTrap.prototype.team = function () {
        return this.bb.readInt8(this.bb_pos + 2);
    };
    RemoveTrap.sizeOf = function () {
        return 4;
    };
    RemoveTrap.createRemoveTrap = function (builder, loc, team) {
        builder.prep(2, 4);
        builder.pad(1);
        builder.writeInt8(team);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return RemoveTrap;
}());
exports.RemoveTrap = RemoveTrap;
