"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.StunAction = void 0;
/**
 * Action for when a robot is stunned
 */
var StunAction = /** @class */ (function () {
    function StunAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    StunAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    StunAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    StunAction.prototype.cooldown = function () {
        return this.bb.readUint16(this.bb_pos + 2);
    };
    StunAction.sizeOf = function () {
        return 4;
    };
    StunAction.createStunAction = function (builder, id, cooldown) {
        builder.prep(2, 4);
        builder.writeInt16(cooldown);
        builder.writeInt16(id);
        return builder.offset();
    };
    return StunAction;
}());
exports.StunAction = StunAction;
