// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Indicates that a robot died and should be removed
 */
@SuppressWarnings("unused")
public final class DieAction extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DieAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Id of the robot that died
   */
  public int id() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  public byte dieType() { return bb.get(bb_pos + 2); }

  public static int createDieAction(FlatBufferBuilder builder, int id, byte dieType) {
    builder.prep(2, 4);
    builder.pad(1);
    builder.putByte(dieType);
    builder.putShort((short) id);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DieAction get(int j) { return get(new DieAction(), j); }
    public DieAction get(DieAction obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

