// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class DieType {
  private DieType() { }
  public static final byte UNKNOWN = 0;
  public static final byte EXCEPTION = 1;

  public static final String[] names = { "UNKNOWN", "EXCEPTION", };

  public static String name(int e) { return names[e]; }
}

