// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Visually indicate a mop attack
 */
@SuppressWarnings("unused")
public final class MopAction extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MopAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Ids of the mopped targets, possibly 0
   */
  public int id0() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  public int id1() { return bb.getShort(bb_pos + 2) & 0xFFFF; }
  public int id2() { return bb.getShort(bb_pos + 4) & 0xFFFF; }

  public static int createMopAction(FlatBufferBuilder builder, int id0, int id1, int id2) {
    builder.prep(2, 6);
    builder.putShort((short) id2);
    builder.putShort((short) id1);
    builder.putShort((short) id0);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MopAction get(int j) { return get(new MopAction(), j); }
    public MopAction get(MopAction obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

