// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class RobotType {
  private RobotType() { }
  public static final byte NONE = 0;
  public static final byte RAT = 1;
  public static final byte RAT_KING = 2;
  public static final byte CAT = 3;

  public static final String[] names = { "NONE", "RAT", "RAT_KING", "CAT", };

  public static String name(int e) { return names[e]; }
}

