// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Adds a marker to the timeline at the current round
 */
@SuppressWarnings("unused")
public final class TimelineMarkerAction extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static TimelineMarkerAction getRootAsTimelineMarkerAction(ByteBuffer _bb) { return getRootAsTimelineMarkerAction(_bb, new TimelineMarkerAction()); }
  public static TimelineMarkerAction getRootAsTimelineMarkerAction(ByteBuffer _bb, TimelineMarkerAction obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TimelineMarkerAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String label() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer labelAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer labelInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createTimelineMarkerAction(FlatBufferBuilder builder,
      int labelOffset) {
    builder.startTable(1);
    TimelineMarkerAction.addLabel(builder, labelOffset);
    return TimelineMarkerAction.endTimelineMarkerAction(builder);
  }

  public static void startTimelineMarkerAction(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addLabel(FlatBufferBuilder builder, int labelOffset) { builder.addOffset(0, labelOffset, 0); }
  public static int endTimelineMarkerAction(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TimelineMarkerAction get(int j) { return get(new TimelineMarkerAction(), j); }
    public TimelineMarkerAction get(TimelineMarkerAction obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

