// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Visually indicate transferring paint from one robot to another
 */
@SuppressWarnings("unused")
public final class TransferAction extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TransferAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Id of the transfer target
   */
  public int id() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  public int amount() { return bb.getInt(bb_pos + 4); }

  public static int createTransferAction(FlatBufferBuilder builder, int id, int amount) {
    builder.prep(4, 8);
    builder.putInt(amount);
    builder.pad(2);
    builder.putShort((short) id);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TransferAction get(int j) { return get(new TransferAction(), j); }
    public TransferAction get(TransferAction obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

