// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class TrapType {
  private TrapType() { }
  public static final byte RAT_TRAP = 0;
  public static final byte CAT_TRAP = 1;

  public static final String[] names = { "RAT_TRAP", "CAT_TRAP", };

  public static String name(int e) { return names[e]; }
}

