// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Upgrade a 3x3 area of rats into a rat king
 */
@SuppressWarnings("unused")
public final class UpgradeToRatKing extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UpgradeToRatKing __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Placeholder data bc the struct cant be empty
   */
  public int phantom() { return bb.getShort(bb_pos + 0) & 0xFFFF; }

  public static int createUpgradeToRatKing(FlatBufferBuilder builder, int phantom) {
    builder.prep(2, 2);
    builder.putShort((short) phantom);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UpgradeToRatKing get(int j) { return get(new UpgradeToRatKing(), j); }
    public UpgradeToRatKing get(UpgradeToRatKing obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

