// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Indicate that this robot was spawned on this turn
 */
@SuppressWarnings("unused")
public final class SpawnAction extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SpawnAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Id of the bot that spawned
   */
  public int id() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  public int x() { return bb.get(bb_pos + 2) & 0xFF; }
  public int y() { return bb.get(bb_pos + 3) & 0xFF; }
  public int dir() { return bb.get(bb_pos + 4) & 0xFF; }
  public byte team() { return bb.get(bb_pos + 5); }
  public byte robotType() { return bb.get(bb_pos + 6); }

  public static int createSpawnAction(FlatBufferBuilder builder, int id, int x, int y, int dir, byte team, byte robotType) {
    builder.prep(2, 8);
    builder.pad(1);
    builder.putByte(robotType);
    builder.putByte(team);
    builder.putByte((byte) dir);
    builder.putByte((byte) y);
    builder.putByte((byte) x);
    builder.putShort((short) id);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SpawnAction get(int j) { return get(new SpawnAction(), j); }
    public SpawnAction get(SpawnAction obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

