// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Throw a rat
 */
@SuppressWarnings("unused")
public final class ThrowRat extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ThrowRat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Id of the thrown rat
   */
  public int id() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  public int loc() { return bb.getShort(bb_pos + 2) & 0xFFFF; }

  public static int createThrowRat(FlatBufferBuilder builder, int id, int loc) {
    builder.prep(2, 4);
    builder.putShort((short) loc);
    builder.putShort((short) id);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ThrowRat get(int j) { return get(new ThrowRat(), j); }
    public ThrowRat get(ThrowRat obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

